
name: Deploy

on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8.7'
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Push to Heroku
              uses: akhileshns/heroku-deploy@v3.11.10
              with:
                heroku_email: "vixting@gmail.com" # Edit this
                heroku_api_key: ${{secrets.HEROKU_API_KEY}},
                heroku_app_name: "discord-tuna-bot" # App name?
                justlogin: true
            - run: |
                git remote add heroku git@heroku.com:discord-tuna-bot.git
                git push heroku master